logLevel = "INFO"
  defaultEntryPoints = ["http", "https"]

debug = false

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "meinedomain.de"
watch = true
exposedByDefault = false

[acme]
email = "meinemail@gmx.de"
storage = "/media/docker/traefik/acme.json"
entryPoint = "https"
acmeLogging=true
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
