defaultEntryPoints = ["http", "https"]
[acme]
email = "meine@example.com"
entryPoint = "https"
onDemand = false
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[web]
address = ":8080"
[web.statistics]
  RecentErrors = 10
  [web.auth.basic]
    users = ["username:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "meinedomain.de"
watch = true
exposedbydefault = false
 [frontends]
   [frontends.docservice]
   backend = "docservice"
   passHostHeader = true

